-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-01-29 01:49:55 EET
--   site:      SQL Server 2012
--   type:      SQL Server 2012



CREATE TABLE dim_account 
    (
     account_key NUMERIC (28) NOT NULL IDENTITY NOT FOR REPLICATION , 
     account_id NUMERIC (28) NOT NULL , 
     district_key NUMERIC (28) , 
     creation_date DATE , 
     frequency VARCHAR (20) , 
     start_date DATE DEFAULT GETDATE() , 
     end_date DATE , 
     current_flag NUMERIC (1) DEFAULT 1 , 
     etl_insert_ts DATETIME DEFAULT CURRENT_TIMESTAMP , 
     etl_batch_id NUMERIC (28) 
    )
GO

ALTER TABLE dim_account ADD CONSTRAINT dim_account_pkey PRIMARY KEY CLUSTERED (account_key)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE dim_card 
    (
     card_key NUMERIC (28) NOT NULL IDENTITY NOT FOR REPLICATION , 
     card_id NUMERIC (28) NOT NULL , 
     disp_id NUMERIC (28) , 
     card_type_key NUMERIC (28) , 
     issued_date DATE , 
     account_key NUMERIC (28) , 
     client_key NUMERIC (28) , 
     start_date DATE DEFAULT GETDATE() , 
     end_date DATE , 
     current_flag NUMERIC (1) DEFAULT 1 , 
     etl_insert_ts DATETIME DEFAULT CURRENT_TIMESTAMP , 
     etl_batch_id NUMERIC (28) 
    )
GO

ALTER TABLE dim_card ADD CONSTRAINT dim_card_pkey PRIMARY KEY CLUSTERED (card_key)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE dim_cardtype 
    (
     card_type_key NUMERIC (28) NOT NULL IDENTITY NOT FOR REPLICATION , 
     card_type VARCHAR (50) 
    )
GO

ALTER TABLE dim_cardtype ADD CONSTRAINT dim_cardtype_pkey PRIMARY KEY CLUSTERED (card_type_key)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE dim_cardtype ADD CONSTRAINT dim_cardtype_unique UNIQUE NONCLUSTERED (card_type)
GO

CREATE TABLE dim_client 
    (
     client_key NUMERIC (28) NOT NULL IDENTITY NOT FOR REPLICATION , 
     client_id NUMERIC (28) NOT NULL , 
     district_key NUMERIC (28) , 
     birth_date DATE , 
     gender CHAR (1) , 
     age_group VARCHAR (10) , 
     start_date DATE DEFAULT GETDATE() , 
     end_date DATE , 
     current_flag NUMERIC (1) DEFAULT 1 , 
     etl_insert_ts DATETIME DEFAULT CURRENT_TIMESTAMP , 
     etl_batch_id NUMERIC (28) 
    )
GO

ALTER TABLE dim_client ADD CONSTRAINT dim_client_pkey PRIMARY KEY CLUSTERED (client_key)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE dim_date 
    (
     date_key NUMERIC (28) NOT NULL IDENTITY NOT FOR REPLICATION , 
     full_date DATE NOT NULL , 
     day NUMERIC (28) , 
     month NUMERIC (28) , 
     quarter NUMERIC (28) , 
     year NUMERIC (28) , 
     weekday NUMERIC (28) , 
     is_weekend NUMERIC (1) 
    )
GO

ALTER TABLE dim_date ADD CONSTRAINT dim_date_pkey PRIMARY KEY CLUSTERED (date_key)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE dim_date ADD CONSTRAINT dim_date_unique UNIQUE NONCLUSTERED (full_date)
GO

CREATE TABLE dim_district 
    (
     district_key NUMERIC (28) NOT NULL IDENTITY NOT FOR REPLICATION , 
     district_id NUMERIC (28) , 
     district_name VARCHAR (50) , 
     region VARCHAR (50) , 
     num_inhabitants NUMERIC (28) , 
     avg_salary NUMERIC (12,2) , 
     num_cities NUMERIC (28) , 
     num_municipalities NUMERIC (28) , 
     unemployment_rate_95 NUMERIC (10,2) , 
     unemployment_rate_96 NUMERIC (10,2) , 
     crimes_95 NUMERIC (28) , 
     crimes_96 NUMERIC (28) , 
     start_date DATE DEFAULT GETDATE() , 
     end_date DATE , 
     current_flag NUMERIC (1) DEFAULT 1 , 
     etl_insert_ts DATETIME DEFAULT CURRENT_TIMESTAMP , 
     etl_batch_id NUMERIC (28) 
    )
GO

ALTER TABLE dim_district ADD CONSTRAINT dim_district_pkey PRIMARY KEY CLUSTERED (district_key)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE dim_district ADD CONSTRAINT dim_district_unique UNIQUE NONCLUSTERED (district_id)
GO

CREATE TABLE dim_k_symbol 
    (
     k_symbol_key NUMERIC (28) NOT NULL IDENTITY NOT FOR REPLICATION , 
     k_symbol_code VARCHAR (20) , 
     description VARCHAR (100) , 
     start_date DATE DEFAULT GETDATE() , 
     end_date DATE , 
     current_flag NUMERIC (1) DEFAULT 1 , 
     etl_insert_ts DATETIME DEFAULT CURRENT_TIMESTAMP , 
     etl_batch_id NUMERIC (28) 
    )
GO

ALTER TABLE dim_k_symbol ADD CONSTRAINT dim_k_symbol_pkey PRIMARY KEY CLUSTERED (k_symbol_key)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE dim_k_symbol ADD CONSTRAINT dim_k_symbol_unique UNIQUE NONCLUSTERED (k_symbol_code)
GO

CREATE TABLE dim_loanstatus 
    (
     loan_status_key NUMERIC (28) NOT NULL IDENTITY NOT FOR REPLICATION , 
     status_code VARCHAR (10) , 
     description VARCHAR (50) 
    )
GO

ALTER TABLE dim_loanstatus ADD CONSTRAINT dim_loanstatus_pkey PRIMARY KEY CLUSTERED (loan_status_key)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE dim_loanstatus ADD CONSTRAINT dim_loanstatus_unique UNIQUE NONCLUSTERED (status_code)
GO

CREATE TABLE dim_transactiontype 
    (
     transaction_type_key NUMERIC (28) NOT NULL IDENTITY NOT FOR REPLICATION , 
     operation VARCHAR (50) 
    )
GO

ALTER TABLE dim_transactiontype ADD CONSTRAINT dim_transtype_pkey PRIMARY KEY CLUSTERED (transaction_type_key)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE dim_transactiontype ADD CONSTRAINT dim_transtype_unique UNIQUE NONCLUSTERED (operation)
GO

CREATE TABLE fact_card 
    (
     card_key NUMERIC (28) NOT NULL IDENTITY NOT FOR REPLICATION , 
     card_id NUMERIC (28) , 
     card_type_key NUMERIC (28) , 
     issued_date NUMERIC (28) , 
     account_key NUMERIC (28) , 
     client_key NUMERIC (28) 
    )
GO

ALTER TABLE fact_card ADD CONSTRAINT fact_card_pkey PRIMARY KEY CLUSTERED (card_key)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE fact_card ADD CONSTRAINT fact_card_unique UNIQUE NONCLUSTERED (card_id)
GO

CREATE TABLE fact_loan 
    (
     loan_key NUMERIC (28) NOT NULL IDENTITY NOT FOR REPLICATION , 
     loan_id NUMERIC (28) , 
     account_key NUMERIC (28) , 
     client_key NUMERIC (28) , 
     district_key NUMERIC (28) , 
     loan_status_key NUMERIC (28) , 
     loan_date NUMERIC (28) , 
     amount NUMERIC (12,2) , 
     duration NUMERIC (28) , 
     payment NUMERIC (12,2) 
    )
GO

ALTER TABLE fact_loan ADD CONSTRAINT fact_loan_pkey PRIMARY KEY CLUSTERED (loan_key)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE fact_loan ADD CONSTRAINT fact_loan_unique UNIQUE NONCLUSTERED (loan_id)
GO

CREATE TABLE fact_transaction 
    (
     transaction_key NUMERIC (28) NOT NULL IDENTITY NOT FOR REPLICATION , 
     trans_id NUMERIC (28) , 
     account_key NUMERIC (28) , 
     client_key NUMERIC (28) , 
     district_key NUMERIC (28) , 
     transaction_type_key NUMERIC (28) , 
     date_key NUMERIC (28) , 
     amount NUMERIC (12,2) , 
     signed_amount NUMERIC (12,2) , 
     balance NUMERIC (12,2) , 
     k_symbol_key NUMERIC (28) , 
     etl_insert_ts DATETIME DEFAULT CURRENT_TIMESTAMP , 
     etl_batch_id NUMERIC (28) 
    )
GO 

    


CREATE NONCLUSTERED INDEX 
    idx_fact_trans_date ON fact_transaction 
    ( 
     date_key 
    ) 
GO 


CREATE NONCLUSTERED INDEX 
    idx_fact_trans_type ON fact_transaction 
    ( 
     transaction_type_key 
    ) 
GO 


CREATE NONCLUSTERED INDEX 
    idx_fact_trans_ksym ON fact_transaction 
    ( 
     k_symbol_key 
    ) 
GO

ALTER TABLE fact_transaction ADD CONSTRAINT fact_trans_pkey PRIMARY KEY CLUSTERED (transaction_key)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE fact_transaction ADD CONSTRAINT fact_trans_unique UNIQUE NONCLUSTERED (trans_id)
GO

ALTER TABLE dim_account 
    ADD CONSTRAINT dim_acc_district_fk FOREIGN KEY 
    ( 
     district_key
    ) 
    REFERENCES dim_district 
    ( 
     district_key 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE dim_card 
    ADD CONSTRAINT dim_card_acc_fk FOREIGN KEY 
    ( 
     account_key
    ) 
    REFERENCES dim_account 
    ( 
     account_key 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE dim_card 
    ADD CONSTRAINT dim_card_client_fk FOREIGN KEY 
    ( 
     client_key
    ) 
    REFERENCES dim_client 
    ( 
     client_key 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE dim_card 
    ADD CONSTRAINT dim_card_type_fk FOREIGN KEY 
    ( 
     card_type_key
    ) 
    REFERENCES dim_cardtype 
    ( 
     card_type_key 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE dim_client 
    ADD CONSTRAINT dim_cli_district_fk FOREIGN KEY 
    ( 
     district_key
    ) 
    REFERENCES dim_district 
    ( 
     district_key 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE fact_card 
    ADD CONSTRAINT fact_card_acc_fk FOREIGN KEY 
    ( 
     account_key
    ) 
    REFERENCES dim_account 
    ( 
     account_key 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE fact_card 
    ADD CONSTRAINT fact_card_client_fk FOREIGN KEY 
    ( 
     client_key
    ) 
    REFERENCES dim_client 
    ( 
     client_key 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE fact_card 
    ADD CONSTRAINT fact_card_date_fk FOREIGN KEY 
    ( 
     issued_date
    ) 
    REFERENCES dim_date 
    ( 
     date_key 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE fact_card 
    ADD CONSTRAINT fact_card_type_fk FOREIGN KEY 
    ( 
     card_type_key
    ) 
    REFERENCES dim_cardtype 
    ( 
     card_type_key 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE fact_loan 
    ADD CONSTRAINT fact_loan_acc_fk FOREIGN KEY 
    ( 
     account_key
    ) 
    REFERENCES dim_account 
    ( 
     account_key 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE fact_loan 
    ADD CONSTRAINT fact_loan_cli_fk FOREIGN KEY 
    ( 
     client_key
    ) 
    REFERENCES dim_client 
    ( 
     client_key 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE fact_loan 
    ADD CONSTRAINT fact_loan_date_fk FOREIGN KEY 
    ( 
     loan_date
    ) 
    REFERENCES dim_date 
    ( 
     date_key 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE fact_loan 
    ADD CONSTRAINT fact_loan_dist_fk FOREIGN KEY 
    ( 
     district_key
    ) 
    REFERENCES dim_district 
    ( 
     district_key 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE fact_loan 
    ADD CONSTRAINT fact_loan_status_fk FOREIGN KEY 
    ( 
     loan_status_key
    ) 
    REFERENCES dim_loanstatus 
    ( 
     loan_status_key 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE fact_transaction 
    ADD CONSTRAINT fact_trans_acc_fk FOREIGN KEY 
    ( 
     account_key
    ) 
    REFERENCES dim_account 
    ( 
     account_key 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE fact_transaction 
    ADD CONSTRAINT fact_trans_cli_fk FOREIGN KEY 
    ( 
     client_key
    ) 
    REFERENCES dim_client 
    ( 
     client_key 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE fact_transaction 
    ADD CONSTRAINT fact_trans_date_fk FOREIGN KEY 
    ( 
     date_key
    ) 
    REFERENCES dim_date 
    ( 
     date_key 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE fact_transaction 
    ADD CONSTRAINT fact_trans_dist_fk FOREIGN KEY 
    ( 
     district_key
    ) 
    REFERENCES dim_district 
    ( 
     district_key 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE fact_transaction 
    ADD CONSTRAINT fact_trans_k_fk FOREIGN KEY 
    ( 
     k_symbol_key
    ) 
    REFERENCES dim_k_symbol 
    ( 
     k_symbol_key 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE fact_transaction 
    ADD CONSTRAINT fact_trans_type_fk FOREIGN KEY 
    ( 
     transaction_type_key
    ) 
    REFERENCES dim_transactiontype 
    ( 
     transaction_type_key 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             3
-- ALTER TABLE                             41
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
