-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-01-29 01:54:10 EET
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE dim_account 
    ( 
     account_key   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     account_id    NUMBER  NOT NULL , 
     district_key  NUMBER , 
     creation_date DATE , 
     frequency     VARCHAR2 (20) , 
     start_date    DATE DEFAULT SYSDATE , 
     end_date      DATE , 
     current_flag  NUMBER (1) DEFAULT 1 , 
     etl_insert_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP , 
     etl_batch_id  NUMBER 
    ) 
    LOGGING 
;

ALTER TABLE dim_account 
    ADD CONSTRAINT dim_account_pkey PRIMARY KEY ( account_key ) ;

CREATE TABLE dim_card 
    ( 
     card_key      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     card_id       NUMBER  NOT NULL , 
     disp_id       NUMBER , 
     card_type_key NUMBER , 
     issued_date   DATE , 
     account_key   NUMBER , 
     client_key    NUMBER , 
     start_date    DATE DEFAULT SYSDATE , 
     end_date      DATE , 
     current_flag  NUMBER (1) DEFAULT 1 , 
     etl_insert_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP , 
     etl_batch_id  NUMBER 
    ) 
    LOGGING 
;

ALTER TABLE dim_card 
    ADD CONSTRAINT dim_card_pkey PRIMARY KEY ( card_key ) ;

CREATE TABLE dim_cardtype 
    ( 
     card_type_key NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     card_type     VARCHAR2 (50) 
    ) 
    LOGGING 
;

ALTER TABLE dim_cardtype 
    ADD CONSTRAINT dim_cardtype_pkey PRIMARY KEY ( card_type_key ) ;

ALTER TABLE dim_cardtype 
    ADD CONSTRAINT dim_cardtype_unique UNIQUE ( card_type ) ;

CREATE TABLE dim_client 
    ( 
     client_key    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     client_id     NUMBER  NOT NULL , 
     district_key  NUMBER , 
     birth_date    DATE , 
     gender        CHAR (1) , 
     age_group     VARCHAR2 (10) , 
     start_date    DATE DEFAULT SYSDATE , 
     end_date      DATE , 
     current_flag  NUMBER (1) DEFAULT 1 , 
     etl_insert_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP , 
     etl_batch_id  NUMBER 
    ) 
    LOGGING 
;

ALTER TABLE dim_client 
    ADD CONSTRAINT dim_client_pkey PRIMARY KEY ( client_key ) ;

CREATE TABLE dim_date 
    ( 
     date_key   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     full_date  DATE  NOT NULL , 
     day        NUMBER , 
     month      NUMBER , 
     quarter    NUMBER , 
     year       NUMBER , 
     weekday    NUMBER , 
     is_weekend NUMBER (1) 
    ) 
    LOGGING 
;

ALTER TABLE dim_date 
    ADD CONSTRAINT dim_date_pkey PRIMARY KEY ( date_key ) ;

ALTER TABLE dim_date 
    ADD CONSTRAINT dim_date_unique UNIQUE ( full_date ) ;

CREATE TABLE dim_district 
    ( 
     district_key         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     district_id          NUMBER , 
     district_name        VARCHAR2 (50) , 
     region               VARCHAR2 (50) , 
     num_inhabitants      NUMBER , 
     avg_salary           NUMBER (12,2) , 
     num_cities           NUMBER , 
     num_municipalities   NUMBER , 
     unemployment_rate_95 NUMBER (10,2) , 
     unemployment_rate_96 NUMBER (10,2) , 
     crimes_95            NUMBER , 
     crimes_96            NUMBER , 
     start_date           DATE DEFAULT SYSDATE , 
     end_date             DATE , 
     current_flag         NUMBER (1) DEFAULT 1 , 
     etl_insert_ts        TIMESTAMP DEFAULT CURRENT_TIMESTAMP , 
     etl_batch_id         NUMBER 
    ) 
    LOGGING 
;

ALTER TABLE dim_district 
    ADD CONSTRAINT dim_district_pkey PRIMARY KEY ( district_key ) ;

ALTER TABLE dim_district 
    ADD CONSTRAINT dim_district_unique UNIQUE ( district_id ) ;

CREATE TABLE dim_k_symbol 
    ( 
     k_symbol_key  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     k_symbol_code VARCHAR2 (20) , 
     description   VARCHAR2 (100) , 
     start_date    DATE DEFAULT SYSDATE , 
     end_date      DATE , 
     current_flag  NUMBER (1) DEFAULT 1 , 
     etl_insert_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP , 
     etl_batch_id  NUMBER 
    ) 
    LOGGING 
;

ALTER TABLE dim_k_symbol 
    ADD CONSTRAINT dim_k_symbol_pkey PRIMARY KEY ( k_symbol_key ) ;

ALTER TABLE dim_k_symbol 
    ADD CONSTRAINT dim_k_symbol_unique UNIQUE ( k_symbol_code ) ;

CREATE TABLE dim_loanstatus 
    ( 
     loan_status_key NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     status_code     VARCHAR2 (10) , 
     description     VARCHAR2 (50) 
    ) 
    LOGGING 
;

ALTER TABLE dim_loanstatus 
    ADD CONSTRAINT dim_loanstatus_pkey PRIMARY KEY ( loan_status_key ) ;

ALTER TABLE dim_loanstatus 
    ADD CONSTRAINT dim_loanstatus_unique UNIQUE ( status_code ) ;

CREATE TABLE dim_transactiontype 
    ( 
     transaction_type_key NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     operation            VARCHAR2 (50) 
    ) 
    LOGGING 
;

ALTER TABLE dim_transactiontype 
    ADD CONSTRAINT dim_transtype_pkey PRIMARY KEY ( transaction_type_key ) ;

ALTER TABLE dim_transactiontype 
    ADD CONSTRAINT dim_transtype_unique UNIQUE ( operation ) ;

CREATE TABLE fact_card 
    ( 
     card_key      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     card_id       NUMBER , 
     card_type_key NUMBER , 
     issued_date   NUMBER , 
     account_key   NUMBER , 
     client_key    NUMBER 
    ) 
    LOGGING 
;

ALTER TABLE fact_card 
    ADD CONSTRAINT fact_card_pkey PRIMARY KEY ( card_key ) ;

ALTER TABLE fact_card 
    ADD CONSTRAINT fact_card_unique UNIQUE ( card_id ) ;

CREATE TABLE fact_loan 
    ( 
     loan_key        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     loan_id         NUMBER , 
     account_key     NUMBER , 
     client_key      NUMBER , 
     district_key    NUMBER , 
     loan_status_key NUMBER , 
     loan_date       NUMBER , 
     amount          NUMBER (12,2) , 
     duration        NUMBER , 
     payment         NUMBER (12,2) 
    ) 
    LOGGING 
;

ALTER TABLE fact_loan 
    ADD CONSTRAINT fact_loan_pkey PRIMARY KEY ( loan_key ) ;

ALTER TABLE fact_loan 
    ADD CONSTRAINT fact_loan_unique UNIQUE ( loan_id ) ;

CREATE TABLE fact_transaction 
    ( 
     transaction_key      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     trans_id             NUMBER , 
     account_key          NUMBER , 
     client_key           NUMBER , 
     district_key         NUMBER , 
     transaction_type_key NUMBER , 
     date_key             NUMBER , 
     amount               NUMBER (12,2) , 
     signed_amount        NUMBER (12,2) , 
     balance              NUMBER (12,2) , 
     k_symbol_key         NUMBER , 
     etl_insert_ts        TIMESTAMP DEFAULT CURRENT_TIMESTAMP , 
     etl_batch_id         NUMBER 
    ) 
    LOGGING 
;
CREATE INDEX idx_fact_trans_date ON fact_transaction 
    ( 
     date_key ASC 
    ) 
;
CREATE INDEX idx_fact_trans_type ON fact_transaction 
    ( 
     transaction_type_key ASC 
    ) 
;
CREATE INDEX idx_fact_trans_ksym ON fact_transaction 
    ( 
     k_symbol_key ASC 
    ) 
;

ALTER TABLE fact_transaction 
    ADD CONSTRAINT fact_trans_pkey PRIMARY KEY ( transaction_key ) ;

ALTER TABLE fact_transaction 
    ADD CONSTRAINT fact_trans_unique UNIQUE ( trans_id ) ;

ALTER TABLE dim_account 
    ADD CONSTRAINT dim_acc_district_fk FOREIGN KEY 
    ( 
     district_key
    ) 
    REFERENCES dim_district 
    ( 
     district_key
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE dim_card 
    ADD CONSTRAINT dim_card_acc_fk FOREIGN KEY 
    ( 
     account_key
    ) 
    REFERENCES dim_account 
    ( 
     account_key
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE dim_card 
    ADD CONSTRAINT dim_card_client_fk FOREIGN KEY 
    ( 
     client_key
    ) 
    REFERENCES dim_client 
    ( 
     client_key
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE dim_card 
    ADD CONSTRAINT dim_card_type_fk FOREIGN KEY 
    ( 
     card_type_key
    ) 
    REFERENCES dim_cardtype 
    ( 
     card_type_key
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE dim_client 
    ADD CONSTRAINT dim_cli_district_fk FOREIGN KEY 
    ( 
     district_key
    ) 
    REFERENCES dim_district 
    ( 
     district_key
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE fact_card 
    ADD CONSTRAINT fact_card_acc_fk FOREIGN KEY 
    ( 
     account_key
    ) 
    REFERENCES dim_account 
    ( 
     account_key
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE fact_card 
    ADD CONSTRAINT fact_card_client_fk FOREIGN KEY 
    ( 
     client_key
    ) 
    REFERENCES dim_client 
    ( 
     client_key
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE fact_card 
    ADD CONSTRAINT fact_card_date_fk FOREIGN KEY 
    ( 
     issued_date
    ) 
    REFERENCES dim_date 
    ( 
     date_key
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE fact_card 
    ADD CONSTRAINT fact_card_type_fk FOREIGN KEY 
    ( 
     card_type_key
    ) 
    REFERENCES dim_cardtype 
    ( 
     card_type_key
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE fact_loan 
    ADD CONSTRAINT fact_loan_acc_fk FOREIGN KEY 
    ( 
     account_key
    ) 
    REFERENCES dim_account 
    ( 
     account_key
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE fact_loan 
    ADD CONSTRAINT fact_loan_cli_fk FOREIGN KEY 
    ( 
     client_key
    ) 
    REFERENCES dim_client 
    ( 
     client_key
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE fact_loan 
    ADD CONSTRAINT fact_loan_date_fk FOREIGN KEY 
    ( 
     loan_date
    ) 
    REFERENCES dim_date 
    ( 
     date_key
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE fact_loan 
    ADD CONSTRAINT fact_loan_dist_fk FOREIGN KEY 
    ( 
     district_key
    ) 
    REFERENCES dim_district 
    ( 
     district_key
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE fact_loan 
    ADD CONSTRAINT fact_loan_status_fk FOREIGN KEY 
    ( 
     loan_status_key
    ) 
    REFERENCES dim_loanstatus 
    ( 
     loan_status_key
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE fact_transaction 
    ADD CONSTRAINT fact_trans_acc_fk FOREIGN KEY 
    ( 
     account_key
    ) 
    REFERENCES dim_account 
    ( 
     account_key
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE fact_transaction 
    ADD CONSTRAINT fact_trans_cli_fk FOREIGN KEY 
    ( 
     client_key
    ) 
    REFERENCES dim_client 
    ( 
     client_key
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE fact_transaction 
    ADD CONSTRAINT fact_trans_date_fk FOREIGN KEY 
    ( 
     date_key
    ) 
    REFERENCES dim_date 
    ( 
     date_key
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE fact_transaction 
    ADD CONSTRAINT fact_trans_dist_fk FOREIGN KEY 
    ( 
     district_key
    ) 
    REFERENCES dim_district 
    ( 
     district_key
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE fact_transaction 
    ADD CONSTRAINT fact_trans_k_fk FOREIGN KEY 
    ( 
     k_symbol_key
    ) 
    REFERENCES dim_k_symbol 
    ( 
     k_symbol_key
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE fact_transaction 
    ADD CONSTRAINT fact_trans_type_fk FOREIGN KEY 
    ( 
     transaction_type_key
    ) 
    REFERENCES dim_transactiontype 
    ( 
     transaction_type_key
    ) 
    NOT DEFERRABLE 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             3
-- ALTER TABLE                             41
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
