-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS dw.dim_account
(
    account_key bigserial NOT NULL,
    account_id bigint NOT NULL,
    district_key bigint,
    creation_date date,
    frequency character varying(20) COLLATE pg_catalog."default",
    start_date date DEFAULT CURRENT_DATE,
    end_date date,
    current_flag boolean DEFAULT true,
    etl_insert_ts timestamp without time zone DEFAULT now(),
    etl_batch_id integer,
    CONSTRAINT dim_account_pkey PRIMARY KEY (account_key)
);

CREATE TABLE IF NOT EXISTS dw.dim_card
(
    card_key bigserial NOT NULL,
    card_id bigint NOT NULL,
    disp_id bigint,
    card_type_key bigint,
    issued_date date,
    account_key bigint,
    client_key bigint,
    start_date date DEFAULT CURRENT_DATE,
    end_date date,
    current_flag boolean DEFAULT true,
    etl_insert_ts timestamp without time zone DEFAULT now(),
    etl_batch_id integer,
    CONSTRAINT dim_card_pkey PRIMARY KEY (card_key)
);

CREATE TABLE IF NOT EXISTS dw.dim_cardtype
(
    card_type_key bigserial NOT NULL,
    card_type character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT dim_cardtype_pkey PRIMARY KEY (card_type_key),
    CONSTRAINT dim_cardtype_card_type_key UNIQUE (card_type)
);

CREATE TABLE IF NOT EXISTS dw.dim_client
(
    client_key bigserial NOT NULL,
    client_id bigint NOT NULL,
    district_key bigint,
    birth_date date,
    gender character(1) COLLATE pg_catalog."default",
    age_group character varying(10) COLLATE pg_catalog."default",
    start_date date DEFAULT CURRENT_DATE,
    end_date date,
    current_flag boolean DEFAULT true,
    etl_insert_ts timestamp without time zone DEFAULT now(),
    etl_batch_id integer,
    CONSTRAINT dim_client_pkey PRIMARY KEY (client_key)
);

CREATE TABLE IF NOT EXISTS dw.dim_date
(
    date_key bigserial NOT NULL,
    full_date date NOT NULL,
    day integer,
    month integer,
    quarter integer,
    year integer,
    weekday integer,
    is_weekend boolean,
    CONSTRAINT dim_date_pkey PRIMARY KEY (date_key),
    CONSTRAINT dim_date_full_date_key UNIQUE (full_date)
);

CREATE TABLE IF NOT EXISTS dw.dim_district
(
    district_key bigserial NOT NULL,
    district_id integer,
    district_name character varying(50) COLLATE pg_catalog."default",
    region character varying(50) COLLATE pg_catalog."default",
    num_inhabitants integer,
    avg_salary numeric(12, 2),
    num_cities integer,
    num_municipalities integer,
    unemployment_rate_95 numeric(10, 2),
    unemployment_rate_96 numeric(10, 2),
    crimes_95 integer,
    crimes_96 integer,
    start_date date DEFAULT CURRENT_DATE,
    end_date date,
    current_flag boolean DEFAULT true,
    etl_insert_ts timestamp without time zone DEFAULT now(),
    etl_batch_id integer,
    CONSTRAINT dim_district_pkey PRIMARY KEY (district_key),
    CONSTRAINT dim_district_district_id_key UNIQUE (district_id)
);

CREATE TABLE IF NOT EXISTS dw.dim_k_symbol
(
    k_symbol_key bigserial NOT NULL,
    k_symbol_code character varying(20) COLLATE pg_catalog."default",
    description character varying(100) COLLATE pg_catalog."default",
    start_date date DEFAULT CURRENT_DATE,
    end_date date,
    current_flag boolean DEFAULT true,
    etl_insert_ts timestamp without time zone DEFAULT now(),
    etl_batch_id integer,
    CONSTRAINT dim_k_symbol_pkey PRIMARY KEY (k_symbol_key),
    CONSTRAINT dim_k_symbol_k_symbol_code_key UNIQUE (k_symbol_code)
);

CREATE TABLE IF NOT EXISTS dw.dim_loanstatus
(
    loan_status_key bigserial NOT NULL,
    status_code character varying(10) COLLATE pg_catalog."default",
    description character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT dim_loanstatus_pkey PRIMARY KEY (loan_status_key),
    CONSTRAINT dim_loanstatus_status_code_key UNIQUE (status_code)
);

CREATE TABLE IF NOT EXISTS dw.dim_transactiontype
(
    transaction_type_key bigserial NOT NULL,
    operation character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT dim_transactiontype_pkey PRIMARY KEY (transaction_type_key),
    CONSTRAINT dim_transactiontype_operation_key UNIQUE (operation)
);

CREATE TABLE IF NOT EXISTS dw.fact_card
(
    card_key bigserial NOT NULL,
    card_id bigint,
    card_type_key bigint,
    issued_date bigint,
    account_key bigint,
    client_key bigint,
    CONSTRAINT fact_card_pkey PRIMARY KEY (card_key),
    CONSTRAINT fact_card_card_id_key UNIQUE (card_id)
);

CREATE TABLE IF NOT EXISTS dw.fact_loan
(
    loan_key bigserial NOT NULL,
    loan_id bigint,
    account_key bigint,
    client_key bigint,
    district_key bigint,
    loan_status_key bigint,
    loan_date bigint,
    amount numeric(12, 2),
    duration integer,
    payment numeric(12, 2),
    CONSTRAINT fact_loan_pkey PRIMARY KEY (loan_key),
    CONSTRAINT fact_loan_loan_id_key UNIQUE (loan_id)
);

CREATE TABLE IF NOT EXISTS dw.fact_transaction
(
    transaction_key bigserial NOT NULL,
    trans_id bigint,
    account_key bigint,
    client_key bigint,
    district_key bigint,
    transaction_type_key bigint,
    date_key bigint,
    amount numeric(12, 2),
    signed_amount numeric(12, 2),
    balance numeric(12, 2),
    k_symbol_key bigint,
    etl_insert_ts timestamp without time zone DEFAULT now(),
    etl_batch_id integer,
    CONSTRAINT fact_transaction_pkey PRIMARY KEY (transaction_key),
    CONSTRAINT fact_transaction_trans_id_key UNIQUE (trans_id)
);

ALTER TABLE IF EXISTS dw.dim_account
    ADD CONSTRAINT dim_account_district_key_fkey FOREIGN KEY (district_key)
    REFERENCES dw.dim_district (district_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dw.dim_card
    ADD CONSTRAINT dim_card_account_key_fkey FOREIGN KEY (account_key)
    REFERENCES dw.dim_account (account_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dw.dim_card
    ADD CONSTRAINT dim_card_card_type_key_fkey FOREIGN KEY (card_type_key)
    REFERENCES dw.dim_cardtype (card_type_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dw.dim_card
    ADD CONSTRAINT dim_card_client_key_fkey FOREIGN KEY (client_key)
    REFERENCES dw.dim_client (client_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dw.dim_client
    ADD CONSTRAINT dim_client_district_key_fkey FOREIGN KEY (district_key)
    REFERENCES dw.dim_district (district_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dw.fact_card
    ADD CONSTRAINT fact_card_account_key_fkey FOREIGN KEY (account_key)
    REFERENCES dw.dim_account (account_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dw.fact_card
    ADD CONSTRAINT fact_card_card_type_key_fkey FOREIGN KEY (card_type_key)
    REFERENCES dw.dim_cardtype (card_type_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dw.fact_card
    ADD CONSTRAINT fact_card_client_key_fkey FOREIGN KEY (client_key)
    REFERENCES dw.dim_client (client_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dw.fact_card
    ADD CONSTRAINT fact_card_issued_date_fkey FOREIGN KEY (issued_date)
    REFERENCES dw.dim_date (date_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dw.fact_loan
    ADD CONSTRAINT fact_loan_account_key_fkey FOREIGN KEY (account_key)
    REFERENCES dw.dim_account (account_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dw.fact_loan
    ADD CONSTRAINT fact_loan_client_key_fkey FOREIGN KEY (client_key)
    REFERENCES dw.dim_client (client_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dw.fact_loan
    ADD CONSTRAINT fact_loan_district_key_fkey FOREIGN KEY (district_key)
    REFERENCES dw.dim_district (district_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dw.fact_loan
    ADD CONSTRAINT fact_loan_loan_date_fkey FOREIGN KEY (loan_date)
    REFERENCES dw.dim_date (date_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dw.fact_loan
    ADD CONSTRAINT fact_loan_loan_status_key_fkey FOREIGN KEY (loan_status_key)
    REFERENCES dw.dim_loanstatus (loan_status_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dw.fact_transaction
    ADD CONSTRAINT fact_transaction_account_key_fkey FOREIGN KEY (account_key)
    REFERENCES dw.dim_account (account_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dw.fact_transaction
    ADD CONSTRAINT fact_transaction_client_key_fkey FOREIGN KEY (client_key)
    REFERENCES dw.dim_client (client_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dw.fact_transaction
    ADD CONSTRAINT fact_transaction_date_key_fkey FOREIGN KEY (date_key)
    REFERENCES dw.dim_date (date_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_fact_transaction_date
    ON dw.fact_transaction(date_key);


ALTER TABLE IF EXISTS dw.fact_transaction
    ADD CONSTRAINT fact_transaction_district_key_fkey FOREIGN KEY (district_key)
    REFERENCES dw.dim_district (district_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dw.fact_transaction
    ADD CONSTRAINT fact_transaction_transaction_type_key_fkey FOREIGN KEY (transaction_type_key)
    REFERENCES dw.dim_transactiontype (transaction_type_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_fact_transaction_type
    ON dw.fact_transaction(transaction_type_key);


ALTER TABLE IF EXISTS dw.fact_transaction
    ADD CONSTRAINT fk_fact_k_symbol FOREIGN KEY (k_symbol_key)
    REFERENCES dw.dim_k_symbol (k_symbol_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_fact_transaction_k_symbol
    ON dw.fact_transaction(k_symbol_key);

END;