-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS source.account
(
    account_id integer NOT NULL,
    district_id integer,
    date date,
    frequency character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

CREATE TABLE IF NOT EXISTS source.bank_transaction
(
    trans_id integer NOT NULL,
    account_id integer,
    date date,
    type character varying(10) COLLATE pg_catalog."default",
    operation character varying(50) COLLATE pg_catalog."default",
    amount numeric,
    balance numeric,
    k_symbol character varying(20) COLLATE pg_catalog."default",
    bank character varying(20) COLLATE pg_catalog."default",
    account character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT bank_transaction_pkey PRIMARY KEY (trans_id)
);

CREATE TABLE IF NOT EXISTS source.card
(
    card_id integer NOT NULL,
    disp_id integer,
    type character varying(20) COLLATE pg_catalog."default",
    issued date,
    CONSTRAINT card_pkey PRIMARY KEY (card_id)
);

CREATE TABLE IF NOT EXISTS source.client
(
    client_id integer NOT NULL,
    district_id integer,
    birth_number integer,
    CONSTRAINT client_pkey PRIMARY KEY (client_id)
);

CREATE TABLE IF NOT EXISTS source.disp
(
    disp_id integer NOT NULL,
    client_id integer,
    account_id integer,
    type character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT disp_pkey PRIMARY KEY (disp_id)
);

CREATE TABLE IF NOT EXISTS source.district
(
    a1 integer NOT NULL,
    a2 character varying(50) COLLATE pg_catalog."default",
    a3 character varying(50) COLLATE pg_catalog."default",
    a4 numeric,
    a5 numeric,
    a6 numeric,
    a7 numeric,
    a8 numeric,
    a9 numeric,
    a10 numeric,
    a11 numeric,
    a12 numeric,
    a13 numeric,
    a14 numeric,
    a15 numeric,
    a16 numeric,
    CONSTRAINT district_pkey1 PRIMARY KEY (a1)
);

CREATE TABLE IF NOT EXISTS source.loan
(
    loan_id integer NOT NULL,
    account_id integer,
    date date,
    amount numeric,
    duration integer,
    payments numeric,
    status character(1) COLLATE pg_catalog."default",
    CONSTRAINT loan_pkey PRIMARY KEY (loan_id)
);

CREATE TABLE IF NOT EXISTS source.permanent_order
(
    order_id integer NOT NULL,
    account_id integer,
    bank_to character varying(20) COLLATE pg_catalog."default",
    account_to character varying(20) COLLATE pg_catalog."default",
    amount numeric,
    k_symbol character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT permanent_order_pkey PRIMARY KEY (order_id)
);

ALTER TABLE IF EXISTS source.account
    ADD CONSTRAINT fk_account_district FOREIGN KEY (district_id)
    REFERENCES source.district (a1) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS source.bank_transaction
    ADD CONSTRAINT fk_transaction_account FOREIGN KEY (account_id)
    REFERENCES source.account (account_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS source.card
    ADD CONSTRAINT fk_card_disp FOREIGN KEY (disp_id)
    REFERENCES source.disp (disp_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS source.client
    ADD CONSTRAINT fk_client_district FOREIGN KEY (district_id)
    REFERENCES source.district (a1) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS source.disp
    ADD CONSTRAINT fk_disp_account FOREIGN KEY (account_id)
    REFERENCES source.account (account_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS source.disp
    ADD CONSTRAINT fk_disp_client FOREIGN KEY (client_id)
    REFERENCES source.client (client_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS source.loan
    ADD CONSTRAINT fk_loan_account FOREIGN KEY (account_id)
    REFERENCES source.account (account_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS source.permanent_order
    ADD CONSTRAINT fk_order_account FOREIGN KEY (account_id)
    REFERENCES source.account (account_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;