-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS staging.stg_account
(
    account_id bigint NOT NULL,
    district_id integer NOT NULL,
    creation_date date,
    frequency character varying(20) COLLATE pg_catalog."default",
    stg_insert_ts timestamp without time zone DEFAULT now(),
    stg_batch_id integer,
    CONSTRAINT stg_account_pkey PRIMARY KEY (account_id)
);

CREATE TABLE IF NOT EXISTS staging.stg_card
(
    card_id bigint NOT NULL,
    disp_id bigint NOT NULL,
    card_type character varying(50) COLLATE pg_catalog."default",
    issued_date date,
    stg_insert_ts timestamp without time zone DEFAULT now(),
    stg_batch_id integer,
    CONSTRAINT stg_card_pkey PRIMARY KEY (card_id)
);

CREATE TABLE IF NOT EXISTS staging.stg_client
(
    client_id bigint NOT NULL,
    district_id integer NOT NULL,
    birth_number text COLLATE pg_catalog."default",
    stg_insert_ts timestamp without time zone DEFAULT now(),
    stg_batch_id integer,
    CONSTRAINT stg_client_pkey PRIMARY KEY (client_id)
);

CREATE TABLE IF NOT EXISTS staging.stg_disposition
(
    disp_id bigint NOT NULL,
    client_id bigint NOT NULL,
    account_id bigint NOT NULL,
    type character varying(50) COLLATE pg_catalog."default",
    stg_insert_ts timestamp without time zone DEFAULT now(),
    stg_batch_id integer,
    CONSTRAINT stg_disposition_pkey PRIMARY KEY (disp_id)
);

CREATE TABLE IF NOT EXISTS staging.stg_district
(
    district_id integer NOT NULL,
    district_name character varying(50) COLLATE pg_catalog."default",
    region character varying(50) COLLATE pg_catalog."default",
    num_inhabitants integer,
    avg_salary numeric(12, 2),
    num_cities integer,
    num_municipalities integer,
    unemployment_rate_95 numeric(10, 2),
    unemployment_rate_96 numeric(10, 2),
    crimes_95 integer,
    crimes_96 integer,
    stg_insert_ts timestamp without time zone DEFAULT now(),
    stg_batch_id integer,
    CONSTRAINT stg_district_pkey PRIMARY KEY (district_id)
);

CREATE TABLE IF NOT EXISTS staging.stg_loan
(
    loan_id bigint NOT NULL,
    account_id bigint NOT NULL,
    loan_date date,
    duration integer,
    amount numeric(12, 2),
    payment numeric(12, 2),
    status character varying(10) COLLATE pg_catalog."default",
    status_desc character varying(20) COLLATE pg_catalog."default",
    stg_insert_ts timestamp without time zone DEFAULT now(),
    stg_batch_id integer,
    CONSTRAINT stg_loan_pkey PRIMARY KEY (loan_id)
);

CREATE TABLE IF NOT EXISTS staging.stg_order
(
    order_id bigint NOT NULL,
    account_id bigint NOT NULL,
    bank_to character varying(20) COLLATE pg_catalog."default",
    account_to bigint,
    amount numeric(12, 2),
    k_symbol character varying(20) COLLATE pg_catalog."default",
    payment_type character varying(20) COLLATE pg_catalog."default",
    stg_insert_ts timestamp without time zone DEFAULT now(),
    stg_batch_id integer,
    CONSTRAINT stg_order_pkey PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS staging.stg_transaction
(
    trans_id bigint NOT NULL,
    account_id bigint NOT NULL,
    transaction_date date,
    operation character varying(50) COLLATE pg_catalog."default",
    amount numeric(12, 2),
    signed_amount numeric(12, 2),
    balance numeric(12, 2),
    k_symbol character varying(20) COLLATE pg_catalog."default",
    bank character varying(20) COLLATE pg_catalog."default",
    account_partner bigint,
    stg_insert_ts timestamp without time zone DEFAULT now(),
    stg_batch_id integer,
    CONSTRAINT stg_transaction_pkey PRIMARY KEY (trans_id)
);
END;